# Generated by Django 5.1.1 on 2024-09-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_alter_room_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation',
        ),
    ]
